name: Playwright Tests by Dynamic Folder

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  detect-folders:
    runs-on: ubuntu-latest
    outputs:
      folders: ${{ steps.set-matrix.outputs.folders }}
    steps:
      - uses: actions/checkout@v4

      - name: Detect test folders
        id: set-matrix
        run: |
          folders=$(find tests -mindepth 1 -maxdepth 1 -type d | sed 's/^/"/; s/$/"/' | paste -sd, -)
          echo "Detected folders JSON array: [$folders]"
          echo "folders=[$folders]" >> "$GITHUB_OUTPUT"

  run-tests:
    needs: detect-folders
    runs-on: ubuntu-latest

    strategy:
      matrix:
        folder: ${{ fromJson(needs.detect-folders.outputs.folders) }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests in ${{ matrix.folder }}
        run: |
          folder="${{ matrix.folder }}"
          echo "Checking for test files in $folder..."
          count=$(find "$folder" -type f \( -name "*.spec.ts" -o -name "*.spec.js" \) | wc -l)
          echo "Found $count test files"
          if [ "$count" -gt 0 ]; then
            npx playwright test "$folder"
            mv playwright-report "playwright-report-$(basename $folder)" || true
          else
            echo "⚠️ No test files found in $folder. Skipping tests."
          fi

      - name: Upload report for ${{ matrix.folder }}
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: report-${{ matrix.folder }}
          path: playwright-report-${{ matrix.folder }}
          retention-days: 30
